{{
    config(
        materialized='view',
        tags=['product', 'staging']
    )
}}

-- Staging model for PRODUCT.PRODUCTS

with source as (
    select * from {{ source('product', 'PRODUCTS') }}
),

renamed as (
    select
        trim(product_id) as product_id,
        trim(product_code) as product_code,
        trim(product_name) as product_name,
        trim(product_description) as product_description,
        trim(short_description) as short_description,
        trim(brand_id) as brand_id,
        trim(primary_category_id) as primary_category_id,
        trim(product_type) as product_type,
        trim(base_uom) as base_uom,
        weight,
        trim(weight_uom) as weight_uom,
        length,
        width,
        height,
        trim(dimension_uom) as dimension_uom,
        is_serialized,
        is_lot_tracked,
        is_perishable,
        shelf_life_days,
        trim(country_of_origin) as country_of_origin,
        trim(hs_code) as hs_code,
        trim(tax_class) as tax_class,
        warranty_months,
        trim(meta_title) as meta_title,
        trim(meta_description) as meta_description,
        trim(meta_keywords) as meta_keywords,
        trim(canonical_url) as canonical_url,
        trim(lifecycle_status) as lifecycle_status,
        launched_at,
        discontinued_at,
        is_active,
        created_at,
        updated_at,
        trim(created_by) as created_by,
        trim(updated_by) as updated_by,
        trim(legacy_product_id) as legacy_product_id,
        trim(old_sku) as old_sku,
        trim(as400_item_code) as as400_item_code,
        trim(sap_material_number) as sap_material_number,
        trim(oracle_item_id) as oracle_item_id,
        trim(migration_source) as migration_source,
        migration_date,
        trim(pre_migration_status) as pre_migration_status,
        trim(legacy_category_code) as legacy_category_code,
        trim(legacy_brand_code) as legacy_brand_code,
        original_create_date,
        trim(source_system_code) as source_system_code,
        trim(shopify_product_id) as shopify_product_id,
        trim(shopify_variant_id) as shopify_variant_id,
        trim(amazon_asin) as amazon_asin,
        trim(walmart_item_id) as walmart_item_id,
        trim(google_product_id) as google_product_id,
        trim(facebook_product_id) as facebook_product_id,
        trim(pinterest_pin_id) as pinterest_pin_id,
        trim(salesforce_product_id) as salesforce_product_id,
        trim(netsuite_item_id) as netsuite_item_id,
        trim(pim_product_id) as pim_product_id,
        cost_price,
        wholesale_price,
        map_price,
        msrp,
        compare_at_price,
        member_price,
        clearance_price,
        last_price_change_date,
        trim(price_change_reason) as price_change_reason,
        margin_pct,
        markup_pct,
        trim(price_tier) as price_tier,
        promotional_price,
        promo_start_date,
        promo_end_date,
        reorder_point,
        reorder_quantity,
        safety_stock,
        lead_time_days,
        trim(abc_classification) as abc_classification,
        trim(velocity_code) as velocity_code,
        last_received_date,
        last_sold_date,
        days_of_supply,
        stockout_count_ytd,
        backorder_allowed,
        dropship_eligible,
        weight_lbs,
        length_in,
        width_in,
        height_in,
        cubic_feet,
        trim(upc_code) as upc_code,
        trim(ean_code) as ean_code,
        trim(gtin) as gtin,
        trim(mpn) as mpn,
        trim(condition_code) as condition_code,
        age_restricted,
        hazmat_flag,
        fda_registered,
        prop65_warning,
        cpsia_compliant,
        energy_star,
        organic_certified,
        fair_trade,
        trim(compliance_status) as compliance_status,
        last_compliance_check,
        demand_forecast_monthly,
        forecast_accuracy,
        trending_score,
        seasonal_index,
        cannibalization_risk,
        trim(cross_sell_affinity) as cross_sell_affinity,
        search_rank,
        recommendation_score,
        return_rate,
        review_sentiment_score,
        temp_discontinue_flag,
        trim(analyst_notes) as analyst_notes,
        review_flag,
        exclude_from_feed,
        test_product_flag,
        sample_product_flag,
        photo_shoot_needed,
        trim(content_review_status) as content_review_status,
        trim(old_category_id) as old_category_id,
        trim(deprecated_brand_id) as deprecated_brand_id,
        trim(v1_product_type) as v1_product_type,
        trim(legacy_tax_code) as legacy_tax_code,
        trim(old_vendor_code) as old_vendor_code,
        trim(previous_upc) as previous_upc,
        archive_flag,
        trim(superseded_by) as superseded_by
    from source
)

select * from renamed
