FROM dbt-bench-base

COPY rpt_order_daily_summary.sql /app/dbt_models_duckdb/models/marts/sales/rpt_order_daily_summary.sql
COPY rpt_order_daily_summary.sql /app/dbt_models_snowflake/models/marts/sales/rpt_order_daily_summary.sql
