FROM ghcr.io/snowflake-labs/data-eng-bench-base:1.0.0

COPY dim_customers.sql /app/dbt_models_duckdb/models/marts/core/dim_customers.sql
COPY dim_customers.sql /app/dbt_models_snowflake/models/marts/core/dim_customers.sql
