{{
    config(
        materialized='view',
        tags=['customer', 'staging']
    )
}}

-- Staging model for CUSTOMER.CUSTOMERS

with source as (
    select * from {{ source('customer', 'CUSTOMERS') }}
),

renamed as (
    select
        trim(customer_id) as customer_id,
        trim(customer_number) as customer_number,
        trim(customer_type) as customer_type,
        trim(email) as email,
        email_verified,
        trim(phone_primary) as phone_primary,
        phone_verified,
        trim(first_name) as first_name,
        trim(last_name) as last_name,
        trim(middle_name) as middle_name,
        trim(company_name) as company_name,
        date_of_birth,
        trim(gender) as gender,
        trim(preferred_language) as preferred_language,
        trim(preferred_currency) as preferred_currency,
        trim(timezone) as timezone,
        tax_exempt,
        trim(tax_exempt_id) as tax_exempt_id,
        trim(acquisition_source) as acquisition_source,
        trim(acquisition_campaign) as acquisition_campaign,
        acquisition_date,
        first_order_date,
        last_order_date,
        total_orders,
        total_lifetime_value,
        trim(current_tier_id) as current_tier_id,
        loyalty_points_balance,
        trim(status) as status,
        is_deleted,
        deleted_at,
        created_at,
        updated_at,
        trim(created_by) as created_by,
        trim(updated_by) as updated_by,
        trim(old_customer_id) as old_customer_id,
        trim(legacy_account_number) as legacy_account_number,
        trim(as400_cust_code) as as400_cust_code,
        trim(siebel_contact_id) as siebel_contact_id,
        trim(oracle_party_id) as oracle_party_id,
        trim(migration_source) as migration_source,
        migration_date,
        trim(migration_batch_id) as migration_batch_id,
        trim(pre_migration_status) as pre_migration_status,
        data_conversion_flag,
        trim(legacy_region_code) as legacy_region_code,
        original_create_date,
        trim(source_system_code) as source_system_code,
        trim(legacy_segment) as legacy_segment,
        converted_from_prospect,
        trim(salesforce_id) as salesforce_id,
        trim(salesforce_account_id__c) as salesforce_account_id__c,
        trim(hubspot_contact_id) as hubspot_contact_id,
        trim(marketo_lead_id) as marketo_lead_id,
        trim(zendesk_user_id) as zendesk_user_id,
        trim(intercom_user_id) as intercom_user_id,
        trim(klaviyo_profile_id) as klaviyo_profile_id,
        trim(stripe_customer_id) as stripe_customer_id,
        trim(shopify_customer_token) as shopify_customer_token,
        trim(segment_anonymous_id) as segment_anonymous_id,
        trim(ga_client_id) as ga_client_id,
        trim(braze_external_id) as braze_external_id,
        trim(temp_segment_2023q4) as temp_segment_2023q4,
        test_flag,
        trim(analyst_notes) as analyst_notes,
        review_flag,
        exclude_from_analysis,
        data_review_date,
        manual_override,
        special_handling_flag,
        covid_adjustment_flag,
        reclass_fy2023,
        trim(deprecated_status_code) as deprecated_status_code,
        trim(old_category_id) as old_category_id,
        trim(v1_customer_type) as v1_customer_type,
        trim(original_source) as original_source,
        trim(legacy_tier) as legacy_tier,
        trim(previous_owner_id) as previous_owner_id,
        archive_flag,
        trim(old_loyalty_status) as old_loyalty_status,
        gdpr_consent_flag,
        gdpr_consent_date,
        trim(gdpr_consent_version) as gdpr_consent_version,
        gdpr_data_subject_request,
        ccpa_do_not_sell,
        ccpa_opt_out_date,
        data_retention_date,
        trim(pii_classification) as pii_classification,
        last_privacy_review,
        sox_control_flag,
        trim(audit_trail_id) as audit_trail_id,
        last_audit_date,
        trim(kyc_status) as kyc_status,
        kyc_verification_date,
        aml_risk_score,
        trim(customer_name_cached) as customer_name_cached,
        trim(primary_email_cached) as primary_email_cached,
        trim(customer_segment_snapshot) as customer_segment_snapshot,
        last_order_total_cached,
        rolling_90_day_revenue,
        lifetime_order_count_cached,
        avg_order_value_cached,
        days_since_last_order,
        trim(preferred_category_cached) as preferred_category_cached,
        customer_tenure_days,
        feature_new_checkout,
        feature_one_click_buy,
        trim(ab_test_pricing_2024) as ab_test_pricing_2024,
        trim(ab_test_ui_redesign) as ab_test_ui_redesign,
        beta_program_flag,
        loyalty_v2_enrolled,
        mobile_app_early_access,
        new_rewards_program,
        churn_risk_score,
        trim(churn_risk_tier) as churn_risk_tier,
        churn_score_date,
        clv_predicted,
        trim(clv_model_version) as clv_model_version,
        propensity_to_buy,
        trim(next_best_offer) as next_best_offer,
        fraud_risk_score,
        trim(segment_ml) as segment_ml,
        cluster_id,
        dq_score,
        dq_last_check,
        dq_email_valid,
        dq_phone_valid,
        dq_address_standardized,
        trim(dq_issues) as dq_issues,
        trim(dedupe_master_id) as dedupe_master_id,
        potential_duplicate_flag,
        email_opt_in_date,
        sms_opt_in,
        direct_mail_opt_out,
        phone_dnc_flag,
        trim(preferred_contact_time) as preferred_contact_time,
        trim(unsubscribe_reason) as unsubscribe_reason,
        trim(experian_income_band) as experian_income_band,
        trim(experian_credit_tier) as experian_credit_tier,
        trim(acxiom_household_id) as acxiom_household_id,
        trim(demographic_cluster) as demographic_cluster,
        trim(firmographic_segment) as firmographic_segment,
        trim(estimated_age_range) as estimated_age_range,
        trim(estimated_income_range) as estimated_income_range,
        homeowner_flag
    from source
)

select * from renamed
